### ISSUE TITLE
Unnecessary warning while creating message template 

### ISSUE THREAD

**Issue by sodium23** [scupid-admin/Morph.ai-Support#76] opened 2018-09-24 14:35 UTC
Create a message template from scratch. It gets created, but shows an unnecessary error message.

![screen shot 2018-09-24 at 8 04 19 pm](https://user-images.githubusercontent.com/14252312/45958448-17ce5d00-c035-11e8-89d7-9d54beb2a896.png)

**Comment by vidzi** [comment] 2018-09-26 09:01
@sodium23 This is not reproducible. 
Can you please help here?
cc: @deemorph

**Comment by ayushmittal29** [comment] 2018-09-26 10:39
I am also getting the unnecessary error - Screen shot attached
![screen shot 2018-09-26 at 4 07 45 pm](https://user-images.githubusercontent.com/42344780/46074895-82eb7100-c1a6-11e8-85ca-1343acadfcc1.png)

**Comment by deemorph** [comment] 2018-09-26 11:06
It's not breaking from backend.

![image](https://user-images.githubusercontent.com/37135525/46075944-b7acf780-c1a9-11e8-82a2-9d7f9469cfd4.png)

I checked in the calls and logs on the server. No error is being returned from the backend. I think it's because of validation in the drop down (Start with a message template)

**Comment by vipul261** [comment] 2018-09-26 12:40
Looks like a UI issue, Assigning this to myself

**Comment by vipul261** [comment] 2018-09-28 09:54
Not reproducible. Re-open with exact steps

**Closed by vipul261** 2018-09-28 09:54 UTC
